### ISSUE TITLE
Deliverable necessari per la valutazione finale

### ISSUE THREAD

**Issue by giodabg** [Loryerba/Gestione_Accessi-GEP2quad-#11]
Controllare la presenza all'interno della cartella Documenti di:

- [x] analisi dei **requisiti**
- [x] **casi d'uso**
- [x] pianificazione con **Project**
- [x] descrizione **GUI** (solo per chi l'ha realizzata)
- [x] diagramma delle **classi** (solo per chi le ha utilizzate)
- [x] diagramma **ER** (solo per chi ha utilizzato un DBMS)
- [x] progetto infrastruttura rete con **Packet Tracer**

Creare
- [x] Un file **install.txt** o .doc o .... il nome dice tutto
- [x] Bozza presentazione power point con **screenshot** che mostrino l'uso da parte dell'utente dei principali casi d'uso
- [x] Foglio excel che riporti un **computo approssimato delle ore totali** dedicate in orario extra- scolastico alle attività di sviluppo del progetto:  **la stima deve essere fatta per ogni componente del gruppo**

**Comment by Cacciaa** [comment]
Done
